### PR TITLE
Fix: handle pagination in ssm describeInstanceInformation & API Rate Limit

### LINKED ISSUE #737: SSM by Tag: Misleading IAM Permission Errors and Rate Limiting Issues
We've observed two related problems when running SSM by tag in large-scale environments:

1. The experiment sometimes reports IAM permission issues even though both the EC2 and litmus service accounts have full SSM permissions
2. The experiment occasionally fails due to AWS API rate limiting, particularly in environments with many instances

### Pagination Issue:
- The current implementation calls `DescribeInstanceInformation` function to fetch a list of EC2 instances managed by SSM
- However, the API returns paginated results. If the target instance is located on a later page, the code may not find it in the initial response
- Ref: check max result [here](https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_DescribeInstanceInformation.html#API_DescribeInstanceInformation_RequestSyntax) and [here](https://pkg.go.dev/github.com/aws/aws-sdk-go/service/ssm#DescribeInstanceInformationInput)
- When an instance isn't found, the error message reports a permission issue, which is misleading given that the necessary `SSM:*` permissions are correctly set

### Rate Limiting Issue:
- When running in environments with many instances, the AWS API may return throttling errors check [here](https://docs.aws.amazon.com/ec2/latest/devguide/ec2-api-throttling.html#api-backoff)
- The current implementation doesn't handle rate limiting properly, causing experiments to fail
- AWS recommends implementing exponential backoff with jitter when dealing with API throttling

## Proposed Solution:

1. **Pagination Handling:**
   - Modify the code to handle pagination properly by using the provided `DescribeInstanceInformationPages` API
   - Adjust the error message so that if an EC2 instance is not found after checking all pages, it reports that the instance could not be located (possibly due to missing tags or other filtering issues), rather than incorrectly indicating an IAM permission error

2. **Rate Limiting:**
   - Implement exponential backoff with jitter when encountering AWS API rate limits
   - Set appropriate maximum retry attempts and total retry duration
   - Add logging to indicate when rate limits are being hit and retries are occurring

## Impact:
Implementing these fixes will:
1. Prevent false-positive permission errors, especially in environments with a large number of instances
2. Make the experiment more resilient against AWS API throttling
3. Provide clearer, more accurate error messaging for users
4. Improve overall reliability in large-scale AWS environments

### PR DESCRIPTION
**Pull request by ThaSami**
**What this PR does / why we need it**:

This PR fixes an issue where experiments running SSM by tag sometimes report misleading IAM permission errors. The root cause is twofold:

1. The implementation of DescribeInstanceInformation did not handle pagination properly. By default, the API returns limited results per page, so if target instances reside on subsequent pages, they won't be found in the first API response—resulting in erroneous permission error messages.

2. The code was not properly handling AWS API rate limits, causing failures during high-volume operations when throttling occurred.

The fix:

- Updates the code to use DescribeInstanceInformationPages to properly iterate through all pages and correctly aggregate instance information
- Implements exponential backoff with jitter when encountering AWS API rate limits

These changes ensure reliable operation even with large numbers of instances and during periods of high API load.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
fixes #737 

**Special notes for your reviewer**:

**Checklist:**
-   [ ] Fixes #<issue number>
-   [ ] PR messages has document related information
-   [ ] Labelled this PR & related issue with `breaking-changes` tag
-   [ ] PR messages has breaking changes related information
-   [ ] Labelled this PR & related issue with `requires-upgrade` tag
-   [ ] PR messages has upgrade related information
-   [ ] Commit has unit tests
-   [ ] Commit has integration tests
-   [ ] E2E run Required for the changes

### CODE REVIEW

File: pkg/cloud/aws/ssm/ssm-operations.go [hunk 1]
```diff
@@ -138,36 +139,74 @@ func CheckInstanceInformation(experimentsDetails *experimentTypes.ExperimentDeta
...
+				for _, instanceDetails := range page.InstanceInformationList {
+					foundInstances[*instanceDetails.InstanceId] = true
+				}
+				return true // continue to next page
+			})
+
 		if err != nil {
+			awsErr := common.CheckAWSError(err)
+			if strings.Contains(awsErr.Error(), "Throttling") ||
+				strings.Contains(awsErr.Error(), "Rate exceeded") {
```
Comment (neelanjan00) [inline pkg/cloud/aws/ssm/ssm-operations.go:170]: NIT: Is there a better way to check for these errors? Maybe some custom error types?

File: pkg/cloud/aws/ssm/ssm-operations.go [hunk 2]
```diff
@@ -138,36 +139,74 @@ func CheckInstanceInformation(experimentsDetails *experimentTypes.ExperimentDeta
...
 	ssmClient := ssm.New(sesh)
-	for _, ec2ID := range instanceIDList {
-		res, err := ssmClient.DescribeInstanceInformation(&ssm.DescribeInstanceInformationInput{})
+	foundInstances := make(map[string]bool)
+	input := &ssm.DescribeInstanceInformationInput{}
+
+	var err error
+	maxRetries := 5
+	maxRetryDuration := time.Second * 30
+	startTime := time.Now()
```
Comment (neelanjan00) [inline pkg/cloud/aws/ssm/ssm-operations.go:152]: NIT: Formatting for better readability.

```suggestion
        var (
 	    foundInstances make(map[string]bool)
	    input &ssm.DescribeInstanceInformationInput{}
	    err error
	    maxRetries = 5
	    maxRetryDuration = time.Second * 30
	    startTime = time.Now()
      )
```

File: pkg/cloud/aws/ssm/ssm-operations.go [hunk 3]
```diff
@@ -138,36 +139,74 @@ func CheckInstanceInformation(experimentsDetails *experimentTypes.ExperimentDeta
...
+
+	for attempt := 0; attempt < maxRetries; attempt++ {
+		if time.Since(startTime) > maxRetryDuration {
+			break
+		}
+
+		err = ssmClient.DescribeInstanceInformationPages(input,
+			func(page *ssm.DescribeInstanceInformationOutput, lastPage bool) bool {
+				for _, instanceDetails := range page.InstanceInformationList {
+					foundInstances[*instanceDetails.InstanceId] = true
```
Comment (neelanjan00) [inline pkg/cloud/aws/ssm/ssm-operations.go:162]: NIT: Ensure `instanceDetails` is not `nil` before dereferencing.

File: pkg/cloud/aws/ssm/ssm-operations.go [hunk 4]
```diff
@@ -138,36 +139,74 @@ func CheckInstanceInformation(experimentsDetails *experimentTypes.ExperimentDeta
...
+		return cerrors.Error{
+			ErrorCode: cerrors.ErrorTypeChaosInject,
+			Reason:    fmt.Sprintf("failed to get instance information after retries: %v", common.CheckAWSError(err).Error()),
+			Target:    fmt.Sprintf("{Region: %v}", experimentsDetails.Region),
+		}
+	}
+
+	// Validate that each target instance is present.
+	for _, ec2ID := range instanceIDList {
+		if !foundInstances[ec2ID] {
```
Comment (neelanjan00) [inline pkg/cloud/aws/ssm/ssm-operations.go:201]: NIT: Should check if the key exists in the map before accessing the associated value.

**Comment by neelanjan00** [comment]
Tagging @uditgaurav for a codeowner review.

File: pkg/cloud/aws/ssm/ssm-operations.go (hunk 4 above)
Comment (ThaSami) [reply pkg/cloud/aws/ssm/ssm-operations.go]: Done.

File: pkg/cloud/aws/ssm/ssm-operations.go (hunk 3 above)
Comment (ThaSami) [reply pkg/cloud/aws/ssm/ssm-operations.go]: Done

File: pkg/cloud/aws/ssm/ssm-operations.go (hunk 1 above)
Comment (ThaSami) [reply pkg/cloud/aws/ssm/ssm-operations.go]: Done

File: pkg/cloud/aws/ssm/ssm-operations.go [hunk 5]
```diff
@@ -138,36 +150,83 @@ func CheckInstanceInformation(experimentsDetails *experimentTypes.ExperimentDeta
...
+				awsErrHasCode(awsErr, "ThrottlingException") ||
+				awsErrHasCode(awsErr, "RequestThrottledException") ||
+				awsErrHasCode(awsErr, "Throttling") ||
+				awsErrHasCode(awsErr, "TooManyRequestsException") ||
+				awsErrHasCode(awsErr, "RequestLimitExceeded") {
+
+				// Calculate exponential backoff with jitter
+				backoffTime := time.Duration(math.Pow(2, float64(attempt))) * time.Second
+				rnd := rand.New(rand.NewSource(time.Now().UnixNano()))
+                                 jitter := time.Duration(rnd.Intn(1000)) * time.Millisecond
```
Comment (uditgaurav) [inline pkg/cloud/aws/ssm/ssm-operations.go:193]:
```suggestion
				 rnd := rand.New(rand.NewSource(time.Now().UnixNano()))
                                 jitter := time.Duration(rnd.Intn(1000)) * time.Millisecond
```

**Review by uditgaurav — APPROVED** [review]

**Comment by uditgaurav** [comment]
Thanks for the update @ThaSami  - pagination and backoff looks great! 🙌

One quick suggestion: Can we use the EC2InstanceTag (format: key:value) as a filter in the DescribeInstanceInformation call?

Right now, we fetch all managed instances. Adding a tag filter lets AWS return only relevant instances, improving performance and reducing API load.

Something like this:

```golang
parts := strings.SplitN(experimentsDetails.EC2InstanceTag, ":", 2)
if len(parts) != 2 {
    return errors.Errorf("invalid EC2InstanceTag %q, expected format key:value", experimentsDetails.EC2InstanceTag)
}
tagKey, tagValue := parts[0], parts[1]

input := &ssm.DescribeInstanceInformationInput{
    Filters: []*ssm.InstanceInformationStringFilter{
        {
            Key:    aws.String(fmt.Sprintf("tag:%s", tagKey)),
            Values: []*string{aws.String(tagValue)},
        },
    },
    MaxResults: aws.Int64(50),
}
```

**Comment by ThaSami** [comment]
@uditgaurav done

**Comment by uditgaurav** [comment]
Looks Good 👍🏻 

<details>
  <summary><strong>SSM Chaos By Tag Logs:</strong></summary>

```
time="2025-04-29T20:12:34Z" level=info msg="Experiment Name: aws-ssm-chaos-by-tag"
time="2025-04-29T20:12:34Z" level=info msg="[PreReq]: Getting the ENV for the aws-ssm-chaos-by-tag experiment"
time="2025-04-29T20:12:36Z" level=info msg="[PreReq]: Updating the chaos result of aws-ssm-chaos-by-tag experiment (SOT)"
time="2025-04-29T20:12:38Z" level=info msg="The instance information is as follows" EC2 Instance Tag="type:chaos" Sequence=parallel Total Chaos Duration=60 Chaos Namespace=litmus
time="2025-04-29T20:12:39Z" level=info msg="[Info]: Targeting the running instances filtered from instance tag" Total number of instances filtered=2 Number of running instances filtered=2
time="2025-04-29T20:12:39Z" level=info msg="[Info]: The target instance have permission to perform SSM API calls"
time="2025-04-29T20:12:41Z" level=info msg="[Info]: SSM docs uploaded successfully"
time="2025-04-29T20:12:41Z" level=info msg="[Chaos]:Number of Instance targeted: 2"
time="2025-04-29T20:12:41Z" level=info msg="[Info]: Target instanceID list, [i-017c83c3926151f7c i-0c146e5776e0fb50b]"
time="2025-04-29T20:12:41Z" level=info msg="[Chaos]: Starting the ssm command"
time="2025-04-29T20:12:41Z" level=info msg="[Wait]: Waiting for the ssm command to get in InProgress state"
time="2025-04-29T20:12:41Z" level=info msg="[Status]: Checking SSM command status"
time="2025-04-29T20:12:43Z" level=info msg="The SSM command status is InProgress"
time="2025-04-29T20:12:45Z" level=info msg="[Wait]: Waiting for the ssm command to get in InProgress state"
time="2025-04-29T20:12:45Z" level=info msg="[Status]: Checking SSM command status"
time="2025-04-29T20:12:45Z" level=info msg="The SSM command status is InProgress"
time="2025-04-29T20:12:49Z" level=info msg="[Wait]: Waiting for the ssm command to get completed"
time="2025-04-29T20:12:49Z" level=info msg="[Status]: Checking SSM command status"
time="2025-04-29T20:12:49Z" level=info msg="The instance state is InProgress"
time="2025-04-29T20:12:51Z" level=info msg="The instance state is InProgress"
time="2025-04-29T20:12:53Z" level=info msg="The instance state is InProgress"
time="2025-04-29T20:12:55Z" level=info msg="The instance state is InProgress"
time="2025-04-29T20:12:57Z" level=info msg="The instance state is InProgress"
time="2025-04-29T20:12:59Z" level=info msg="The instance state is InProgress"
time="2025-04-29T20:13:02Z" level=info msg="The instance state is InProgress"
time="2025-04-29T20:13:04Z" level=info msg="The instance state is InProgress"
time="2025-04-29T20:13:06Z" level=info msg="The instance state is InProgress"
time="2025-04-29T20:13:08Z" level=info msg="The instance state is InProgress"
time="2025-04-29T20:13:10Z" level=info msg="The instance state is InProgress"
time="2025-04-29T20:13:12Z" level=info msg="The instance state is InProgress"
time="2025-04-29T20:13:14Z" level=info msg="The instance state is InProgress"
time="2025-04-29T20:13:16Z" level=info msg="The instance state is InProgress"
time="2025-04-29T20:13:18Z" level=info msg="The instance state is InProgress"
time="2025-04-29T20:13:20Z" level=info msg="The instance state is InProgress"
time="2025-04-29T20:13:22Z" level=info msg="The instance state is InProgress"
time="2025-04-29T20:13:24Z" level=info msg="The instance state is InProgress"
time="2025-04-29T20:13:26Z" level=info msg="The instance state is InProgress"
time="2025-04-29T20:13:28Z" level=info msg="The instance state is InProgress"
time="2025-04-29T20:13:30Z" level=info msg="The instance state is InProgress"
time="2025-04-29T20:13:32Z" level=info msg="The instance state is InProgress"
time="2025-04-29T20:13:34Z" level=info msg="The instance state is InProgress"
time="2025-04-29T20:13:36Z" level=info msg="The instance state is InProgress"
time="2025-04-29T20:13:38Z" level=info msg="The instance state is InProgress"
time="2025-04-29T20:13:40Z" level=info msg="The instance state is InProgress"
time="2025-04-29T20:13:42Z" level=info msg="The SSM command status is Success"
time="2025-04-29T20:13:44Z" level=info msg="[Wait]: Waiting for the ssm command to get completed"
time="2025-04-29T20:13:44Z" level=info msg="[Status]: Checking SSM command status"
time="2025-04-29T20:13:44Z" level=info msg="The SSM command status is Success"
time="2025-04-29T20:13:46Z" level=info msg="[Wait]: Waiting for chaos interval of 60s"
time="2025-04-29T20:14:47Z" level=info msg="[Confirmation]: aws-ssm-chaos-by-tag chaos has been injected successfully"
time="2025-04-29T20:14:49Z" level=info msg="[Probe]: The http probe information is as follows" Mode=EOT Phase=PostChaos Name=healthcheck URL="https://www.google.com/" Run Properties="{5s 2s 0 2 2s 0  2s  false}"
time="2025-04-29T20:14:49Z" level=info msg="[Probe]: HTTP get method informations" ResponseTimeout=5s Name=healthcheck URL="https://www.google.com/" Criteria="==" ResponseCode=200
time="2025-04-29T20:14:49Z" level=info msg="[Probe]: {Actual value: 200}, {Expected value: 200}, {Operator: ==}"
time="2025-04-29T20:14:51Z" level=info msg="[Probe]: healthcheck probe has been Passed 😄 " ProbeInstance=PostChaos ProbeStatus=Passed ProbeName=healthcheck ProbeType=httpProbe
time="2025-04-29T20:14:51Z" level=info msg="[The End]: Updating the chaos result of aws-ssm-chaos-by-tag experiment (EOT)"
```

</details>

**Review by uditgaurav — APPROVED** [review]

**Review by neelanjan00 — APPROVED** [review]
